routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
Route::post('/', ['as' => 'products.search', 'uses' => 'ProductsController@index']);
Route::get('/gamelist', ['as' => 'products.gamelist', 'uses' => 'ProductsController@gamelist']);
Route::get('/blacklist', ['as' => 'products.blacklist', 'uses' => 'ProductsController@blacklist']);
Route::get('/faq', ['as' => 'pages.faq', 'uses' => function() {
    return view('pages.faq');
}]);
Route::get('/contacts', ['as' => 'pages.contacts', 'uses' => function() {
    return view('pages.contacts');
}]);

Route::get('login', ['middleware' => 'admin', 'as' => 'login', 'uses' => 'Admin\Controller@login']);
Route::post('login', ['as' => 'login.post', 'uses' => 'Admin\Controller@auth']);

Route::group(['middleware' => 'admin'], function() {
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function() {
        Route::get('/', ['as' => 'admin.index', 'uses' => 'Controller@index']);
        
        Route::get('users/{id}/delete', ['as' => 'admin.users.delete', 'uses' => 'Controller@userDelete']);
        Route::post('users/store', ['as' => 'admin.users.store', 'uses' => 'Controller@userStore']);
        
        Route::get('products/{id}/unneed', ['as' => 'admin.products.unneed', 'uses' => 'Controller@productUnneed']);
        Route::get('products/unneed', ['as' => 'admin.products.unneed.all', 'uses' => 'Controller@productUnneedAll']);
        Route::post('products/need', ['as' => 'admin.products.need', 'uses' => 'Controller@productsNeed']);
        
        Route::post('products/unneed', ['as' => 'admin.products.unneed.store', 'uses' => 'Controller@productsUnneed']);
        Route::get('products/ununneed', ['as' => 'admin.products.ununneed.all', 'uses' => 'Controller@productsUnunneedAll']);
        Route::get('products/{id}/ununneed', ['as' => 'admin.product.ununneed', 'uses' => 'Controller@productUnunneed']);
        
        Route::get('products/{id}/unindex', ['as' => 'admin.products.unindex', 'uses' => 'Controller@productUnindex']);
        Route::get('products/unindex', ['as' => 'admin.products.unindex.all', 'uses' => 'Controller@productUnindexAll']);
        Route::post('products/index', ['as' => 'admin.products.to_index', 'uses' => 'Controller@productsIndex']);
        
        Route::get('products/{id}/unfix', ['as' => 'admin.products.unfix', 'uses' => 'Controller@productUnfix']);
        Route::get('products/unfix', ['as' => 'admin.products.unfix.all', 'uses' => 'Controller@productUnfixAll']);
        Route::post('products/fix', ['as' => 'admin.products.fix', 'uses' => 'Controller@productsFix']);
        Route::post('products/fix/message', ['as' => 'admin.products.fix.message', 'uses' => 'Controller@productsFixMessage']);

        Route::get('commissions/{id}/delete', ['as' => 'admin.commissions.delete', 'uses' => 'Controller@commissionDelete']);
        Route::get('commissions/delete', ['as' => 'admin.commissions.delete.all', 'uses' => 'Controller@commissionDeleteAll']);
        Route::post('commissions/store', ['as' => 'admin.commissions.store', 'uses' => 'Controller@commissionStore']);
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Swap\Laravel\Facades\Swap;

use App\Services\CommissionService;
use App\Services\ProductCommissionService;

class Product extends Model
{
    protected $primaryKey = 'g2a_product_id';
    protected $table = 'products';
    protected $fillable = ['g2a_product_id', 'name', 'commission', 'price', 'is_fixed','is_needed', 'is_not_needed', 'is_index', 'amount', 'quantity', 'platform', 'publisher', 'is_not_needed_force'];
    public $timestamps = false;
    
    public function getQtyAttribute() {
        return $this->amount - $this->quantity;
    }
    public function getCommissionAttribute() {
        // return 1;
        if($this->is_fixed) return $this->attributes['commission'];
        $commission = ProductCommissionService::commission($this->price);
        //dd($commission);
        if(is_null($commission)) return $this->attributes['commission'];
        return $commission->percent;
    }

    public function price($type, $currency) {
        try {
            switch($currency) {
                case "USD":
                    $rate = 1;
                break;
                case "RUB":
                    $rate = Swap::latest('USD/RUB');
                    $rate = $rate->getValue();
                break;
                default:
                    $rate = Swap::latest('USD/RUB');
                    $rate = $rate->getValue();

                    $_rate = Swap::latest($currency.'/RUB');
                    $rate = $rate / ($_rate->getValue() == 0 ? 1 : $_rate->getValue());
                break;
            }
        } catch(\Throwable $e) {
            $rate = 1;
        }
        
        $commission = CommissionService::commission($this->price);
        if(is_null($commission)) $percent = 100;
        else $percent = $commission->percent;
        
        switch($type) {
            case "our_profit":
                $result = $this->price * $rate * (1 - $this->commission - (100 - $percent)/100);
            break;
            case "your_profit":
                $result = $this->price * $rate * $this->commission;
            break;
            case "g2a_price":
                $result = $this->price * $rate;
            break;
            case "g2a_commission":
                $result = $this->price * $rate * (100 - $percent)/100;                
            break;
            default:
                $result = $rate * $this->price;
            break;
        }
        return number_format($result, 2, ',', '');
    }
}

resources/views/admin/tabs/commissions.blade.php
<h3 class="statistics__title">Формула комиссии</h3>
<form class="statistics__controls" action="{{ route('admin.commissions.store') }}" method="POST">
    {{ csrf_field() }}
    <div class="statistics__range mb-3 mb-sm-0">
        <label class="statistics__label">
            <input class="statistics__input" type="text" name="min_limit" />
            <span class="statistics__subtext">От</span>
        </label>
        <span class="statistics__divider">-</span>
        <label class="statistics__label">
            <input class="statistics__input" type="text" name="max_limit" />
            <span class="statistics__subtext">До</span>
        </label>
    </div>
    <div class="ml-auto">
        <label class="statistics__label">
            <input class="statistics__input" type="text" name="percent" />
            <span class="statistics__subtext">Процент</span>
        </label>
        <button class="btn btn-primary statistics__button" type="submit">
            Добавить
        </button>
    </div>
</form>

<div class="d-flex mb-3">
    <a class="btn btn-primary admin__button ml-auto" href="{{ route('admin.commissions.delete.all') }}">
        Удалить все
    </a>
</div>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th class="table__title" scope="col">
                    Категория цены
                </th>
                <th scope="col">Процент для формулы</th>
                <th scope="col">Действие</th>
                <th scope="col" class="table__blank"></th>
            </tr>
        </thead>
        <tbody>
            @foreach($commissions as $commissiion)
                <tr>
                    <td class="table__title">
                        От {{ $commissiion->min_limit }} до {{ $commissiion->max_limit }} USD
                    </td>
                    <td>{{ $commissiion->percent }}</td>
                    <td><a href="{{ route('admin.commissions.delete', $commissiion->id) }}">Удалить</a></td>
                    <td class="table__blank"></td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

resources/views/admin/tabs/excepted.blade.php
<div class="row mb-5">
    <div class="col-auto">
        <form class="mb-5" method="POST" action="{{ route('admin.products.unneed.store') }}">
            {{ csrf_field() }}
            <textarea class="info__area" id="id-list" placeholder="Список ID..." name="ids">@foreach($products->where('is_not_needed_force', true)->all() as $product) {{ $product->g2a_product_id }}@endforeach</textarea>
            <div class="info__controls">
                <button class="btn btn-primary" type="submit">
                    Добавить
                </button>
            </div>
        </form>
    </div>
</div>

<div class="d-flex mb-3">
    <a class="btn btn-primary admin__button ml-auto" href="{{ route('admin.products.ununneed.all') }}">
        Удалить все
    </a>
</div>
<div class="table-responsive">
    <table class="table table-datatable">
        <thead>
            <tr>
                <th class="table__title" scope="col">
                    <span>ID товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th class="table__title" scope="col">
                    <span>Название товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Выплата</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Требуемое количество</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Продаваемое количество</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Дейсвие</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach($products->where('is_not_needed_force', true) as $product)
                <tr>
                    <td class="table__title">{{ $product->g2a_product_id }}</td>
                    <td class="table__title">{{ $product->name }}</td>
                    <td>{{ $product->price }} USD</td>
                    <td>{{ $product->qty }}</td>
                    <td>{{ $product->quantity }}</td>
                    <td><a href="{{ route('admin.product.ununneed', $product->g2a_product_id) }}">Снять FORCE unneed</a></td>
                </tr>
            @endforeach            
        </tbody>
    </table>
</div>

resources/views/admin/tabs/fixed.blade.php
<div class="row mb-5">
    <div class="col-auto">
        <form class="mb-5" method="POST" action="{{ route('admin.products.fix') }}">
            {{ csrf_field() }}
            <textarea class="info__area" id="id-list" placeholder="Список ID..." name="ids"></textarea>
            <div class="info__controls">
                <button class="btn btn-primary" type="submit">
                    Добавить
                </button>
            </div>
        </form>

        <form method="POST" action="{{ route('admin.products.fix.message') }}">
            {{ csrf_field() }}
            <textarea class="info__area info__area_small" id="warning-id-message" name="message" placeholder="Ваше предупреждение...">{{ App\Setting::find('is_fixed_message')->value }}</textarea>
            <div class="info__controls">
                <button class="btn btn-primary" type="submit">
                    Сохранить
                </button>
            </div>
        </form>
    </div>
</div>

<div class="d-flex mb-3">
    <a class="btn btn-primary admin__button ml-auto" href="{{ route('admin.products.unfix.all') }}">
        Удалить все
    </a>
</div>

<div class="table-responsive">
    <table class="table table-datatable">
        <thead>
            <tr>
                <th class="table__title" scope="col">
                    <span>ID товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th class="table__title" scope="col">
                    <span>Название товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Выплата</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Действие</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach($products->where('is_fixed', true) as $product)
                <tr>
                    <td class="table__title">{{ $product->g2a_product_id }}</td>
                    <td class="table__title">{{ $product->name }}</td>
                    <td>{{ $product->price }} USD</td>
                    <td>
                        <a href="{{ route('admin.products.unfix', $product->g2a_product_id) }}">Снять фиксацию</a>
                    </td>
                </tr>
            @endforeach            
        </tbody>
    </table>
</div>

resources/views/admin/tabs/index.blade.php
<div class="row mb-5">
    <div class="col-auto">
        <form class="mb-5" method="POST" action="{{ route('admin.products.to_index') }}">
            {{ csrf_field() }}
            <textarea class="info__area" name="ids" id="main-id-list" placeholder="Список ID которые будут отображаться на галвном..."></textarea>
            <div class="info__controls">
                <button class="btn btn-primary" type="submit">
                    Добавить
                </button>
            </div>
        </form>
    </div>
</div>

<div class="d-flex mb-3">
    <a class="btn btn-primary admin__button ml-auto" href="{{ route('admin.products.unindex.all') }}">
        Удалить все
    </a>
</div>

<div class="table-responsive">
    <table class="table table-datatable">
        <thead>
            <tr>
                <th class="table__title" scope="col">
                    <span>ID товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th class="table__title" scope="col">
                    <span>Название товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Выплата</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Действие</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach($products->where('is_index', true) as $product)
                <tr>
                    <td class="table__title">{{ $product->g2a_product_id }}</td>
                    <td class="table__title">{{ $product->name }}</td>
                    <td>{{ $product->price }} USD</td>
                    <td>
                        <a href="{{ route('admin.products.unindex', $product->g2a_product_id) }}">Снять с главной страницы</a>
                    </td>
                </tr>
            @endforeach            
        </tbody>
    </table>
</div>

resources/views/admin/tabs/needed.blade.php
<div class="row mb-5">
    <div class="col-auto">
        <form class="mb-5" method="POST" action="{{ route('admin.products.need') }}">
            {{ csrf_field() }}
            <textarea class="info__area" name="ids" id="main-id-list" placeholder="Список ID которые будут отображаться на галвном..."></textarea>
            <div class="info__controls">
                <button class="btn btn-primary" type="submit">
                    Добавить
                </button>
            </div>
        </form>
    </div>
</div>

<div class="d-flex mb-3">
    <a class="btn btn-primary admin__button ml-auto" href="{{ route('admin.products.unneed.all') }}">
        Удалить все
    </a>
</div>

<div class="table-responsive">
    <table class="table table-datatable">
        <thead>
            <tr>
                <th class="table__title" scope="col">
                    <span>ID товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th class="table__title" scope="col">
                    <span>Название товара</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Выплата</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
                <th scope="col">
                    <span>Действие</span>
                    <svg class="icon table__icon icon-up" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#up-arrow"></use>
                    </svg>
                    <svg class="icon table__icon icon-down" width="14" height="14" aria-hidden="true">
                        <use xlink:href="/images/sprite.svg#down-arrow"></use>
                    </svg>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach($products->where('is_needed', true) as $product)
                <tr>
                    <td class="table__title">{{ $product->g2a_product_id }}</td>
                    <td class="table__title">{{ $product->name }}</td>
                    <td>{{ $product->price }} USD</td>
                    <td>
                        <a href="{{ route('admin.products.unneed', $product->g2a_product_id) }}">Снять потребность</a>
                    </td>
                </tr>
            @endforeach            
        </tbody>
    </table>
</div>

resources/views/admin/tabs/users.blade.php
<h3 class="statistics__title">Пользователи системы</h3>
<form class="statistics__controls" action="{{ route('admin.users.store') }}" method="POST" style="width:auto">
    {{ csrf_field() }}
    <div>
        <label class="statistics__label">
            <input class="statistics__input" style="width: 180px" type="text" name="name" />
            <span class="statistics__subtext">Name</span>
        </label>
        <label class="statistics__label">
            <input class="statistics__input" style="width: 180px" type="text" name="email" />
            <span class="statistics__subtext">Email</span>
        </label>
        <label class="statistics__label">
            <input class="statistics__input" style="width: 180px" type="text" name="password" />
            <span class="statistics__subtext">Password</span>
        </label>
        <label class="statistics__label">
            <input class="statistics__input" style="width: 180px" type="text" name="public_key" />
            <span class="statistics__subtext">Client Public</span>
        </label>
        <label class="statistics__label">
            <input class="statistics__input" style="width: 180px" type="text" name="secret_key" />
            <span class="statistics__subtext">Client Secret</span>
        </label>
        <button class="btn btn-primary statistics__button" type="submit">
            Добавить
        </button>
    </div>
</form>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th class="table__title" scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Client Public</th>
                <th scope="col">Client Secret</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach($users->where('name', '!=', 'root') as $user)
                <tr>
                    <td class="table__title">{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->public_key }}</td>
                    <td>{{ $user->secret_key }}</td>
                    <td><a href="{{ route('admin.users.delete', $user->id) }}">Удалить</a></td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>